import os

# --- 配置区 ---
# 排除不需要显示在页面上的文件夹（如 Git 配置文件或脚本本身）
EXCLUDE_DIRS = {'.git', '.github', 'assets', 'css', 'js', '__pycache__'}
# 页面标题
PAGE_TITLE = "文件存储库索引"

def generate_html():
    # 1. 获取当前目录下所有的文件夹，并过滤掉排除名单
    try:
        dirs = [d for d in os.listdir('.') if os.path.isdir(d) and d not in EXCLUDE_DIRS]
        dirs.sort()  # 按字母顺序排序
    except Exception as e:
        print(f"读取目录失败: {e}")
        return

    # 2. 构建 HTML 内容
    # 使用了简单的 CSS 让页面在手机和电脑上看起来都比较舒服
    html_content = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{PAGE_TITLE}</title>
    <style>
        body {{ font-family: -apple-system, sans-serif; line-height: 1.6; padding: 20px; background-color: #f6f8fa; color: #24292f; }}
        .container {{ max-width: 800px; margin: 0 auto; background: #fff; padding: 30px; border-radius: 8px; border: 1px solid #d0d7de; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
        h1 {{ font-size: 24px; border-bottom: 1px solid #d0d7de; padding-bottom: 10px; margin-top: 0; }}
        ul {{ list-style: none; padding: 0; }}
        li {{ border-bottom: 1px solid #ebf0f4; }}
        li:last-child {{ border-bottom: none; }}
        a {{ display: block; padding: 12px 10px; text-decoration: none; color: #0969da; font-weight: 500; transition: 0.2s; }}
        a:hover {{ background-color: #f3f4f6; color: #0a4a91; }}
        .icon {{ margin-right: 10px; font-size: 1.1em; }}
        .footer {{ margin-top: 20px; font-size: 12px; color: #57606a; text-align: center; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>📁 {PAGE_TITLE}</h1>
        <ul>
            {"".join([f'<li><a href="./{d}/"><span class="icon">📂</span>{d}/</a></li>' for d in dirs])}
        </ul>
        <div class="footer">Auto Generated By Py</div>
    </div>
</body>
</html>"""

    # 3. 写入 index.html 文件
    try:
        with open('index.html', 'w', encoding='utf-8') as f:
            f.write(html_content)
        print("✨ Success! index.html updated, {} folders in total.".format(len(dirs)))
    except Exception as e:
        print(f"Failed to write file: {e}")

if __name__ == "__main__":
    generate_html()
